Feat/handson
sfeir-open-source/sfeir-school-kubernetes pull request #1
Opened 2019-09-02 19:36 UTC by Ameausoone

2019-09-04 09:29 UTC, zbbfufu requested changes

2019-09-04 09:29 UTC, zbbfufu commented on README.md
> +La formation se déroule step by step, les TP se trouve dans le dossier [`steps/`](steps).
"les TPs se trouvent"

2019-09-04 09:29 UTC, zbbfufu commented on terraform/gke/gke-variables.tf
> +variable "gke_cluster_name" {
Le nom de la variable et la valeur par défaut ne semblent pas cohérents.

2019-09-05 07:18 UTC, Tony-Proum requested changes

2019-09-05 07:18 UTC, Tony-Proum commented on README.md
> +La formation se déroule step by step, les TP se trouve dans le dossier [`steps/`](steps).
```suggestion
La formation se déroule step by step, les TP se trouvent dans le dossier [`steps/`](steps).
```

2019-09-09 11:51 UTC, merged