docs(theme_migration) migrated school to sfeir-theme v2
sfeir-open-source/sfeir-school-kubernetes pull request #9
Opened 2020-04-06 16:20 UTC by Sourcemancien

* MDs are indexed into `scripts/slides.js` instead of `index.html`
* replaced k8s.scss and css by slides ones
* purged duplicated resources directories as `libs`
* replaced some medias for better integration
* fixed some slides due to new markdown-parsing constraints

2020-04-07 06:07 UTC, jefBinomed requested changes

2020-04-07 06:07 UTC, jefBinomed commented on .gitignore
> +web_modules/
faut pas l'ajouter au gitignore sinon la github pages ne marchera pas. L'idée d'avoir le web_modules est d'avoir un endroit unique dans lequel on commit nos dépendances de libraires.

2020-04-07 06:07 UTC, jefBinomed commented on docs/markdown/00-school/00-TITLE.md
> +<strong>Feuille de présence (obligatoire)</strong><br>
tu pouvais juste rajouter un retour à la ligne pour être sur que ton **Feuille de présence ... soit pris en compte

2020-04-07 07:52 UTC, Sourcemancien commented on .gitignore
> +web_modules/
Effectivement je me suis cru face à un répertoire de build local
C'est corrigé et j'ai bien tracké le répertoire

2020-04-07 07:53 UTC, Sourcemancien commented on docs/markdown/00-school/00-TITLE.md
> +<strong>Feuille de présence (obligatoire)</strong><br>
j'avais oublié cette possibilité, du coup j'ai remis la ligne en MD comme ça ça me fait un mémo

2020-04-08 06:34 UTC, jefBinomed approved these changes

2020-04-08 07:17 UTC, merged